name: Sync Hugging Face Space to GitHub

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Optional: Runs daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use a compatible Python version

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Download files from Hugging Face Space
        run: |
          python -c "
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id='andresampa/CtB-AI-img-gen-Python', repo_type='space', local_dir='./space_files')
          "

      - name: Commit and push files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./space_files
          git commit -m "Sync files from Hugging Face Space"
          git push
